- Home Server:
    - Pi-hole:
        icon: pi-hole.png
        href: http://{{HOMEPAGE_VAR_HOST_IP}}:80/admin
        description: Ad blocking
        server: &local my-docker
        container: pihole
        widget:
          type: pihole
          url: http://{{HOMEPAGE_VAR_HOST_IP}}:80
          key: {{HOMEPAGE_VAR_PIHOLE_PASSWORD}} 

    - Home Assistant:
        icon: home-assistant.png
        href: http://{{HOMEPAGE_VAR_HOST_IP}}:8123
        description: Smart Home
        server: *local
        container: homeassistant

    - Seafile:
        icon: seafile.png
        href: http://{{HOMEPAGE_VAR_HOST_IP}}:8000
        description: Cloud Storage
        server: *local
        container: seafile

- Utilities:
    - Portainer:
        icon: portainer.png
        href: https://{{HOMEPAGE_VAR_HOST_IP}}:9443
        description: Docker Management
        server: *local
        container: portainer
        widget:
          type: portainer
          url: https://{{HOMEPAGE_VAR_HOST_IP}}:9443
          env: 3
          key: {{HOMEPAGE_VAR_PORTAINER_ACCESS_KEY}}

    - Gluetun:
        icon: gluetun.png
        href: http://{{HOMEPAGE_VAR_HOST_IP}}:8001
        description: VPN Tunnel
        container: gluetun
        widget:
            type: gluetun
            url: http://{{HOMEPAGE_VAR_HOST_IP}}:8001

    - Flaresolverr:
        icon: flaresolverr.png
        href: http://{{HOMEPAGE_VAR_HOST_IP}}:8191
        description: Cloudflare Proxy
        container: flaresolverr
        # No specific widget, but will show UP/DOWN status automatically
    - Code Server:
        icon: visual-studio-code.png
        href: http://{{HOMEPAGE_VAR_HOST_IP}}:8443
        description: VS Code in Browser
        server: *local
        container: code_server

- Media:
    - Jellyfin:
        icon: jellyfin.png
        href: http://{{HOMEPAGE_VAR_HOST_IP}}:8096
        description: Media Streaming
        server: *local
        container: jellyfin
        widget:
          type: jellyfin
          url: http://{{HOMEPAGE_VAR_HOST_IP}}:8096
          key: {{HOMEPAGE_VAR_JELLYFIN_API_KEY}}
          enableBlocks: true
          enableNowPlaying: true
          enableUser: true
          enableMediaControl: true
          showEpisodeNumber: true
          expandOneStreamToTwoRows: true

    - qBittorrent:
        icon: qbittorrent.png
        href: http://{{HOMEPAGE_VAR_HOST_IP}}:8080
        description: Torrent Downloader
        server: *local
        container: qbittorrent
        widget:
          type: qbittorrent
          url: http://{{HOMEPAGE_VAR_HOST_IP}}:8080
          username: {{HOMEPAGE_VAR_QBITTORRENT_USERNAME}}
          password: {{HOMEPAGE_VAR_QBITTORRENT_PASSWORD}}

    - Radarr:
        icon: radarr.png
        href: http://{{HOMEPAGE_VAR_HOST_IP}}:7878
        description: Movie Manager
        server: *local
        container: radarr
        widget:
          type: radarr
          url: http://{{HOMEPAGE_VAR_HOST_IP}}:7878
          key: {{HOMEPAGE_VAR_RADARR_API_KEY}}

    - Prowlarr:
        icon: prowlarr.png
        href: http://{{HOMEPAGE_VAR_HOST_IP}}:9696
        description: Indexer Manager
        server: *local
        container: prowlarr
        widget:
          type: prowlarr
          url: http://{{HOMEPAGE_VAR_HOST_IP}}:9696/
          key: {{HOMEPAGE_VAR_PROWLARR_API_KEY}}
